name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.21.0'

      - name: Install dependencies
        run: npm install

      - name: Run linters
        run: npm run lint

      - name: Run formatters check
        run: npm run format:check

      - name: Check commit messages
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: commitlint.config.cjs
